name: Permissions testing
on:
  push:
    branches:
    - main
  pull_request: 
  workflow_dispatch: 
jobs:
  test:
    name: Permissions testing
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
    - uses: actions/checkout@v2
